// @ladino/schemas — contratos Zod compartidos, fuente única del OpenAPI
// (ADR-0004, ADR-0015). Paquete PURO: zod y nada más.
export {
  CreateCompanyRequest,
  CompanyResponse,
  ListCompaniesResponse,
  MePermissionsResponse,
  OnboardBusinessRequest,
  OnboardBusinessResponse,
  MemberAssignment,
  MemberResponse,
  ListMembersResponse,
  AddMemberRequest,
  SetMemberStatusRequest,
  SetCompanyFiscalAddressRequest,
  UpdateCompanyProfileRequest,
  SetCompanyTaxIdRequest,
  CorrectCompanyTaxIdRequest,
  MyProfileResponse,
  SetMyProfileRequest,
  ErrorResponse,
} from "./companies.js";
export {
  AmountString,
  MoneyInput,
  CreateProductRequest,
  CreateProductSimpleRequest,
  ProductSimpleResponse,
  ImportProductsRowResult,
  ImportProductsResponse,
  ImportNumberFormat,
  ProductImportRow,
  ProductImportPreviewResponse,
  ProductImportJobRowResult,
  ProductImportJobResponse,
  UpdateProductRequest,
  SetProductTaxCategoryRequest,
  ProductResponse,
  ListProductsResponse,
  CreatePriceListRequest,
  PriceListResponse,
  SetPriceRequest,
  PriceItemResponse,
} from "./products.js";
export {
  QuantityString,
  FxInput,
  ReceiveStockRequest,
  ReceiveStockApiRequest,
  IssueStockRequest,
  AdjustStockRequest,
  TransferStockRequest,
  InventoryMoveResponse,
  ListInventoryMovesResponse,
  StockBalanceResponse,
  ListStockResponse,
  CreateWarehouseRequest,
  UpdateWarehouseRequest,
  WarehouseResponse,
  TransferResponse,
  RecipeLineRequest,
  SetRecipeRequest,
  RecipeLineResponse,
  RecipeResponse,
  ConsumeRecipeRequest,
  ConsumeRecipeResponse,
  CreateProductTemplateRequest,
  ProductTemplateResponse,
  TemplateStockResponse,
  SetStockThresholdRequest,
  LowStockResponse,
  ExpiringLotsResponse,
} from "./inventory.js";
export {
  CustomerStatus,
  CreateCustomerRequest,
  UpdateCustomerRequest,
  SetCustomerTaxIdRequest,
  SetCustomerBlockedRequest,
  CustomerResponse,
  ListCustomersResponse,
} from "./customers.js";
export {
  DocumentKind,
  DocumentStatus,
  PaymentInstrument,
  DocumentLineRequest,
  CreateQuoteRequest,
  CreateOrderRequest,
  ConfirmOrderRequest,
  CreateInvoiceRequest,
  AnnulInvoiceRequest,
  RegisterPaymentRequest,
  CreateReturnRequest,
  DocumentLineResponse,
  DocumentResponse,
  PaymentResponse,
  ExchangeGainLossResponse,
  DocumentDetailResponse,
  ListDocumentsResponse,
  RegisterPaymentResponse,
  IgtfOnPayment,
  PosQuoteRequest,
  PosQuoteLine,
  PosQuoteResponse,
  QuickSalePaymentInput,
  QuickSaleRequest,
  PosTenderRequest,
  PosTenderResponse,
  QuickSaleResponse,
  CreateDirectCreditNoteRequest,
  DirectCreditNoteResponse,
  CreateDebitNoteRequest,
  PosCartLine,
  UpsertPosCartRequest,
  PosCartResponse,
  ListPosCartsResponse,
  PosChangeResponse,
  ReturnResponse,
  AgingResponse,
  CustomerStatementResponse,
  CreateFiscalRangeRequest,
  CompleteFiscalRangePrinterRequest,
  CorrectFiscalRangePrinterRequest,
  CancelFiscalRangeRequest,
  FiscalRangeResponse,
  CreateExchangeRateRequest,
  RegisterContingencyRangeRequest,
  ContingencyRangeResponse,
  RegisterContingencyInvoiceRequest,
  CloseContingencyRequest,
  FiscalSetupResponse,
  SalesMode,
  RefundCustomerCreditRequest,
  CustomerRefundResponse,
  AssignFiscalRegimeRequest,
  AcceptIvaGeneralRequest,
  AcceptIvaGeneralResponse,
} from "./sales.js";
export {
  SupplierKind,
  AllocationMethod,
  PurchaseInstrument,
  CreateSupplierRequest,
  SupplierResponse,
  ListSuppliersResponse,
  PurchaseLineRequest,
  CreatePurchaseOrderRequest,
  ReceiveGoodsLineRequest,
  ReceiveGoodsRequest,
  RegisterSupplierInvoiceRequest,
  ApplyLandedCostRequest,
  RegisterSupplierCreditNoteRequest,
  RegisterSupplierPaymentRequest,
  SimplePurchaseRequest,
  SimplePurchaseResponse,
  CreateRetentionRuleRequest,
  PurchaseOrderResponse,
  GoodsReceiptResponse,
  SupplierRetentionResponse,
  SupplierInvoiceResponse,
  MatchingResponse,
  LandedCostResponse,
  RetentionReceiptResponse,
  SupplierPaymentResponse,
  ApAgingResponse,
  SupplierStatementResponse,
  ListPurchaseOrdersResponse,
  ArrivalLineRequest,
  RegisterArrivalRequest,
  ArrivalResponse,
  ArrivalImpactResponse,
  ClosePurchaseOrderRequest,
  IvaRetentionFullReason,
  RetentionExclusionMark,
  RetentionVoucherLineResponse,
  RetentionVoucherResponse,
  CorrectRetentionVoucherRequest,
  DeliverRetentionVoucherRequest,
  SetRetentionVoucherModeRequest,
} from "./purchases.js";
export {
  AccountKind,
  AccountNature,
  EntryStatus,
  CreateAccountRequest,
  UpdateAccountRequest,
  AccountResponse,
  ImportChartTemplateRequest,
  JournalLineRequest,
  CreateJournalEntryRequest,
  PostJournalEntryRequest,
  ReverseJournalEntryRequest,
  DiscardJournalEntryRequest,
  JournalLineResponse,
  JournalEntryResponse,
  JournalEntryDetailResponse,
  ListJournalEntriesResponse,
  LedgerResponse,
  TrialBalanceResponse,
  FiscalPeriodResponse,
  ClosePeriodRequest,
  ReopenPeriodRequest,
  YearEndCloseRequest,
  SetAccountPurposeRequest,
  CreateJournalTemplateRequest,
  PendingJournalResponse,
  IncomeStatementResponse,
  BalanceSheetResponse,
} from "./accounting.js";
export {
  TreasuryAccountKind,
  PaymentMethodKind,
  CompanyAccountResponse,
  CreateCompanyAccountRequest,
  UpdateCompanyAccountRequest,
  ListCompanyAccountsResponse,
  PaymentMethodResponse,
  CreatePaymentMethodRequest,
  UpdatePaymentMethodRequest,
  ListPaymentMethodsResponse,
  AccountingOutcome,
  RegisterExpenseRequest,
  CreateTreasuryTransferRequest,
  TreasuryTransferResponse,
  ExpenseResponse,
  ListExpensesResponse,
  CloseCashRegisterRequest,
  CashClosingResponse,
  ListCashClosingsResponse,
  KeepDailyRateRequest,
  DailyRateResponse,
  CandidateAccountResponse,
  CandidatesByInstrument,
  ListCandidateAccountsResponse,
  MoneyLandingGapResponse,
  ListMoneyLandingGapsResponse,
} from "./treasury.js";
export {
  NegocioResumenResponse,
  ConvertResponse,
  CompanySettingsResponse,
  UpdateCompanySettingsRequest,
} from "./negocio.js";
export {
  BookKind,
  TaxTreatment,
  SalesBookRow,
  PurchasesBookRow,
  IvaRetentionBookRow,
  IslrRetentionBookRow,
  FiscalBookResponse,
  BookReconciliationResponse,
  BookFormatAdapterResponse,
  ExportFiscalBookRequest,
  FiscalBookRunResponse,
  ExportFiscalBookResponse,
  ExportSalesBookSummaryRequest,
  ExportSalesBookSummaryResponse,
  ListFiscalBookRunsResponse,
} from "./fiscal-books.js";
export {
  RegisterSupportedRetentionRequest,
  SupportedRetentionResponse,
  RegisterSupportedRetentionResponse,
  ListSupportedRetentionsResponse,
  GenerateIvaPeriodRequest,
  IvaPeriodDetalleAlicuota,
  IvaPeriodResultResponse,
  ListIvaPeriodResultsResponse,
  IvaPeriodProposalResponse,
  TaxCalendarObligation,
  TaxCalendarResponse,
  FiscalObligation,
  LoadFiscalDeadlinesRequest,
  FiscalDeadlineResponse,
  ListFiscalDeadlinesResponse,
} from "./declarations.js";
export {
  IgtfInstrument,
  EnableIgtfRequest,
  SetIgtfInstrumentRequest,
  IgtfInstrumentResponse,
  IgtfStatusResponse,
  SetCompanyTaxpayerTypeRequest,
  SetCompanyTaxpayerTypeResponse,
  CompanyTaxpayerTypeCode,
  CompanyTaxpayerTypePeriod,
  CompanyTaxpayerTypeResponse,
  IgtfPerceptionResponse,
  ListIgtfPerceptionsResponse,
  PosIgtfPreviewResponse,
} from "./igtf.js";

// El documento de identidad: una sola función para normalizar, validar y mostrar (A-08, M-05).
export {
  LETRAS_RIF,
  MARCADOR_SIN_RIF,
  esMarcadorSinRif,
  normalizarDocumento,
  digitoVerificadorRif,
  leerRif,
  leerDocumentoCliente,
  avisoDigitoRif,
  formatearDocumento,
} from "./rif.js";
export type { LetraRif, DigitoRif, LecturaDocumento } from "./rif.js";

// El número de un documento con su serie, igual en todas partes (ADR-0071, H11).
export { serieYNumero, serieYNumeroImpreso } from "./documento-numero.js";
export {
  CARACTERES_FILA_DESCRIPCION,
  CARACTERES_FILA_MOTIVO,
  partirEnFilas,
  filasDeDescripcion,
  filasDelMotivo,
} from "./forma-libre.js";
